### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by ylluminate** [ArtemkaKun/FastVlangVisualization#2]
Nice work, I too can't wait to see this implemented in V fully!

Thought: you might link up this repo to the main app page for folks to find easily.  Also, you might use the more clear date format of YYYY-MM-DD since others are so ambiguous or take a moment to grok... Just a thought.

Thanks!

**Comment by ArtemkaKun** [comment]
Hi, thanks :) 

About linking this stuff on the - will be done asap
About date format - I will think about that, not a big deal, but I need to do a small UX/UI R&D

**Comment by ArtemkaKun** [comment]
Date format - done
Link to the project - done
